### ISSUE TITLE
Unable to install on Mac OS

### ISSUE THREAD

**Issue by maxjiang93** [pyvista/pymeshfix#1]
Line 33 in setup.py should be commented out, at least for MacOS system. Else the following error occurs:

error: invalid argument '-std=gnu++11' not allowed with 'C'
error: command 'gcc' failed with exit status 1

**Comment by akaszynski** [comment]
Thanks for catching that.  I don’t usually test against Mac OS, so I’ll add a conditional compiler flag since I think this is a necessary option for at least windows.

Can you confirm this works for Mac OS?

**Comment by maxjiang93** [comment]
Yeah I can confirm that commenting the line out works for MacOS.

Max
