### ISSUE TITLE
Fill hole for non-watertight planar mesh

### ISSUE THREAD

**Issue by BinWang0213** [pyvista/pymeshfix#13]
Hi,

I'd like to fix a planar mesh. meshfix always tring to convert it into a volume.
 Is there any way to do it using meshfix?
![Capture](https://user-images.githubusercontent.com/20053787/70356590-57e4be80-183a-11ea-8953-92806b3ef34f.PNG)

[PlaneSTL.zip](https://github.com/pyvista/pymeshfix/files/3934018/PlaneSTL.zip)

**Comment by banesullivan** [comment]
@akaszynski , can meahfix handle non-manifold meshes like this?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by supersubscript** [comment]
This is also something I'd be interested in! A lot of the meshes I work with on a day-to-day basis are partially open, but can still contain smaller holes that I'd like to repair

**Comment by akaszynski** [comment]
This will get you 90% there:

```python
import numpy as np
import pyvista as pv

from pymeshfix._meshfix import PyTMesh
filename = 'PlaneSTL.ply'

orig_mesh = pv.read(filename)
mfix = PyTMesh(False)
mfix.load_file(filename)

# Fills all the holes having at least 'nbe' boundary edges. If
# 'refine' is true, adds inner vertices to reproduce the
# sampling density of the surroundings. Returns number of holes
# patched.  If 'nbe' is 0 (default), all the holes are patched.
mfix.fill_small_boundaries(nbe=100, refine=True)

vert, faces = mfix.return_arrays()

triangles = np.empty((faces.shape[0], 4))
triangles[:, -3:] = faces
triangles[:, 0] = 3

mesh = pv.PolyData(vert, triangles)
mesh.plot()
```

![tmp](https://user-images.githubusercontent.com/11981631/70393076-cfefe780-19e6-11ea-8c9d-252a7d7485d9.png)

The python `MeshFix` class doesn't have all the features of the lower level cython wrapped `PyTMesh` class.  Once I get a free moment, I'll code that in so it's possible to perform finer level mesh repair in the python class.

The trick is using `fill_small_boundaries`, and controlling the maximum hole fill size with `nbe`, which is the maximum number of edges that a hole being filled is allowed to have.  The cython documentation has this wrong, so ignore it for now.  Another note, is that it seems there is a limit to the repair algorithm whereby some of the holes that include only a single point are not filled.  These boundary holes are not detected by `vtk`'s hole repair algorithm either.  Hence only being 90% there.

**Comment by BinWang0213** [comment]
This looks great. I can use it now. You may can add an example to address this kind of planar hole fixing problem.

**Comment by BinWang0213** [comment]
The meshfix seems can not fix this one. Do you have any idea of this?

![image](https://user-images.githubusercontent.com/20053787/70404357-5f08f980-19ff-11ea-857f-1d6404df597e.png)

[PlanarSTL2.zip](https://github.com/pyvista/pymeshfix/files/3937721/PlanarSTL2.zip)

**Comment by akaszynski** [comment]
Copied and pasted and ended up with an acceptable result:

```python
import numpy as np
import pyvista as pv

from pymeshfix._meshfix import PyTMesh
filename = 'PlanarSTL2.stl'

orig_mesh = pv.read(filename)
mfix = PyTMesh(False)
mfix.load_file(filename)

# Fills all the holes having at least 'nbe' boundary edges. If
# 'refine' is true, adds inner vertices to reproduce the
# sampling density of the surroundings. Returns number of holes
# patched.  If 'nbe' is 0 (default), all the holes are patched.
mfix.fill_small_boundaries(nbe=100, refine=True)

vert, faces = mfix.return_arrays()

triangles = np.empty((faces.shape[0], 4))
triangles[:, -3:] = faces
triangles[:, 0] = 3

mesh = pv.PolyData(vert, triangles)
mesh.plot()
```

![tmp](https://user-images.githubusercontent.com/11981631/70404563-ce500f00-1a3a-11ea-82d6-093313acc6b6.png)

**Comment by BinWang0213** [comment]
Thanks for your rapid reply. It works now. But I need to convert save my mesh first and using meshfix to load the mesh from disk instead of memory.

Here is my code now
```python
def planarHoleFilling(verts,facets,numEdges=100):
    from pymeshfix._meshfix import PyTMesh
    
    #Save mesh into a temp file
    mfix_t = PyTMesh(False)
    vert=np.asarray(verts)
    facets=np.asarray(facets)
    mfix_t.load_array(vert, facets)
    mfix_t.save_file("temp.stl")
    
    #Load mesh from file
    mfix = PyTMesh(False)
    mfix.load_file("temp.stl")
    #mfix.load_array(vert, facets) #This will triagger problem

    # Fills all the holes having at least 'nbe' boundary edges. If
    # 'refine' is true, adds inner vertices to reproduce the
    # sampling density of the surroundings. Returns number of holes
    # patched.  If 'nbe' is 0 (default), all the holes are patched.
    mfix.fill_small_boundaries(nbe=numEdges, refine=True)
        
    v, f = mfix.return_arrays()
    
    #mfix.save_file("PlanarSTL2.stl")
    
    triangles = np.empty((f.shape[0], 4))
    triangles[:, -3:] = f
    triangles[:, 0] = 3

    mesh = pv.PolyData(v, triangles)
    return mesh
```

**Comment by akaszynski** [comment]
Totally spaced on this question.  Is this still an issue @BinWang0213?
