### ISSUE TITLE
Loading a mesh to fill holes in it .obj file

### ISSUE THREAD

**Issue by popupdev** [pyvista/pymeshfix#18]
I tried repair() to fill holes in my mesh .
But it cutted my mesh into half and filled  areas within it ..
Can it be solved..

And also my mesh has vertex colors and how can I extract textures from it.

**Comment by banesullivan** [comment]
Can you provide the OBJ file and your code so that we can reproduce the issue?

**Comment by akaszynski** [comment]
Closing stale issue without code/meshes.
