### ISSUE TITLE
Does Pymeshfix has anything to remove overlapping mesh regions

### ISSUE THREAD

**Issue by popupdev** [pyvista/pymeshfix#19]
I have 2 mesh which are similar not exactly same  but has 30-35% similarities..
I combined  them using **concatenate()** in trimesh library

Like one mesh on another

But after concatenation I find places where the lower mesh overlaps at certain places above the upper mesh..
Is there any function to remove only the overlapping parts of the lower positioned mesh..without using any backend like blender..

For eg Take a look at the image below :

![maxresdefault (1)](https://user-images.githubusercontent.com/56559624/81989054-29290a80-965a-11ea-8aec-fc56f0089874.jpg)

Thanks in advance for anyone who took time to go through it ..

**Comment by akaszynski** [comment]
I don't think that you'll be able to use `meshfix` for this.  Meshfix is primarily suited for generating manifold meshes from meshes with holes or degenerate faces, and while it might work to remove the overlapping regions, I doubt it would generate a reasonable output mesh.

**Comment by popupdev** [comment]
>  it might work to remove the overlapping regions

How can this be done..

**Comment by akaszynski** [comment]
Could you please show me the sample code you’ve tried and upload your meshes here?

**Comment by banesullivan** [comment]
You might also play around with PyVista's [`clean()`](https://docs.pyvista.org/core/filters.html#pyvista.PolyDataFilters.clean) method after merging the meshes

**Comment by akaszynski** [comment]
Closing stale issue without code/meshes.
