### ISSUE TITLE
Original connectivity preserving during self-intersection repairing

### ISSUE THREAD

**Issue by MaxMayya** [pyvista/pymeshfix#31]
Thank you for sharing this work.
Can you confirm that the self-intersection repairing algorithm does NOT preserve the original mesh's connectivity (number of points and their connections in-between)?
Many thanks

**Comment by akaszynski** [comment]
> Can you confirm that the self-intersection repairing algorithm does NOT preserve the original mesh's connectivity (number of points and their connections in-between)?

This appears to be the case.
