### ISSUE TITLE
Error- float property expected

### ISSUE THREAD

**Issue by GSonakshi** [pyvista/pymeshfix#40]
```py
import pyvista as pv
from pymeshfix._meshfix import PyTMesh
mfix = PyTMesh('output2.ply')  # False removes extra verbose output
mfix.load_file(planar_mesh)
```
On calling load_file function (which is an inbuilt function of PyTMesh) the program exits with error code 255 and the kernel stops. I have attached the .ply file.
Any help will be appreciated.
Thanks
[output2.ply.zip](https://github.com/pyvista/pymeshfix/files/7575411/output2.ply.zip)

**Comment by akaszynski** [comment]
File must have been in an invalid format, because reading it in with `pyvista` and outputting it fixed it:

```py
import pyvista as pv
from pymeshfix._meshfix import PyTMesh

mesh = pv.read('output2.ply')
mesh.save('mesh.ply')

mfix = PyTMesh()  # False removes extra verbose output
mfix.load_file('mesh.ply')
```

```
Loading ..113%
INFO- Loaded 35207 vertices and 80126 faces.
WARNING- Some cuts were necessary to cope with non manifold configuration.
```

**Comment by GSonakshi** [comment]
It worked thanks
