### ISSUE TITLE
Docs: LoadFile() should be load_file()

### ISSUE THREAD

**Issue by itan1** [pyvista/pymeshfix#50]
The documentation mentions `tin.LoadFile(infile)` but this should be `tin.load_file(infile)`. Occurences:

- [pymeshfix/cython/_meshfix.pyx](https://github.com/pyvista/pymeshfix/blob/5dd08101cd7001dbc3bce37b36099fec83c47834/pymeshfix/cython/_meshfix.pyx)
- [/README.rst](https://github.com/pyvista/pymeshfix/blob/a7f91fcb8443604761b1f5c37386ae83942dc225/README.rst)

**Comment by banesullivan** [comment]
We should add docstring tests to verify these. Thanks for raising!
