### ISSUE TITLE
Better error message on instantiation

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pymeshfix#6]
https://github.com/pyvista/pymeshfix/blob/1c13b0525bb5c789714ab8ba8dd555d0aade1ed4/pymeshfix/meshfix.py#L22-L36

Should we include a more user-friendly error message here?

Because if we pass a PyVista mesh that isn't PolyData, then this error gets thrown... this could be very confusing for a new user.

Also, what if we added a catch to automatically cast things like UnstructuredGrids to PolyData and use a `.tri_filter` to ensure it is a triangular mesh?

```py
.extract_geometry().tri_filter()
```

Thoughts, @akaszynski?

**Comment by akaszynski** [comment]
Agreed and addressed in 72c1479b8009ea48568f01e815741c2de48af53f.  I don't think it makes sense to allow the user to load in solid UnstructuredGrids as those are already manifold, but I did improve the messaging, allowed ``vtk`` surfaces, and implemented a ``tri_filter`` for non-triangular meshes.
