### ISSUE TITLE
New release for numpy 2.0 necessary?

### ISSUE THREAD

**Issue by Stavr0sStuff** [pyvista/pymeshfix#65]
Hi,

Is it possible we need a new release of pymeshfix now that numpy 2.0.0 is out? Or update dependency requirements in `setup.py` so that only numpy 1.X is supported?

I get the following error during unit tests of a library that uses `pymeshfix`

> lib\my-lib\dev\meshfix.py:9: in <module>
>     from pymeshfix import _meshfix
> .venv\lib\site-packages\pymeshfix\__init__.py:2: in <module>
>     from pymeshfix import _meshfix  # noqa: F401
> pymeshfix\\cython\\_meshfix.pyx:1: in init pymeshfix._meshfix
>     ???
> E   ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
> ------------------------------- Captured stderr -------------------------------
> 
> A module that was compiled using NumPy 1.x cannot be run in
> NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
> versions of NumPy, modules must be compiled with NumPy 2.0.
> Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
> 
> If you are a user of the module, the easiest solution will be to
> downgrade to 'numpy<2' or try to upgrade the affected module.
> We expect that some modules will need time to support NumPy 2.
>

**Comment by akaszynski** [comment]
You’re correct that one or the other is needed. I’m tempted to see if nanobind supports both simultaneously.

**Comment by akaszynski** [comment]
Updated in https://pypi.org/project/pymeshfix/0.17.0/
